[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
btg_locking_period = "vrccD48wXDoZbj9t6xu7X2362Lr9yyocMB7aq9GVaym"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.mainnet.openverse.network"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
