[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
btg_locking_period = "99mpy2LmaD747bwWSLs5sNHPuRRPMdd1aR22HeAceqUh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://api.mainnet.openverse.network:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
