[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
btg_stake_mint = "vrca8nDGAZW9R23jAerRJUqsd7vz1q3sqkKMxQsisxk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://api.mainnet.openverse.network:8899"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
