[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
btg_stake_mint = "13LuL7scpzXTa5hCgs7LYpeTfpcdNcU9DkuW1rMqHYQU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.mainnet.openverse.network"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
